### ISSUE TITLE
time:get "week" is not working (or is not explained adequately)

### ISSUE THREAD

**Issue by SFRailsback** [charlesres/time#6]
time:get "week" returns a value between 0 and 7 for any date, whereas I expected it to produce values between 1 and 52 for the 52 weeks per year. An example:
12/28/2090 7:43:16.888 resulted in a value of  6. 

In any case, the documentation needs updating to explain exactly what "week" returns, including which day of the year is assumed to be the start of week 1. (Excel has two options.)

**Comment by charlesres** [comment]
@SFRailsback. Thanks for reporting this issue. It seems I used dayofyear / 52 instead of dayofyear / 7 for calculating the number of weeks from the first day of the year. I'll add a fix for it. 
One thing I should add is that the expected number of weeks relies on the first day of the year instead of the calendar week, which might be confusing to some. I'll probably have to update that section to better reflect the expected calendar week.
